apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-configmap
  namespace: postgresql
  labels:
    app: postgresql
data:
  POSTGRES_DB: observability
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: admin
